blank_issues_enabled: false
contact_links:
  - name: Pytania ogólne
    url: https://github.com/ORGANIZACJA/REPOZYTORIUM/discussions
    about: Sprawy spoza zakresu Słownika Upraw kieruj do Dyskusji.
